export const GET_PLACES = 'GET_PLACES';
export const SELECT_PLACE = 'SELECT_PLACE';

export const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE';

export const GET_PLACE_DETAIL = 'GET_PLACE_DETAIL';

export const GET_PLACE_DETAIL_REQUEST = 'GET_PLACE_DETAIL_REQUEST';
export const GET_PLACE_DETAIL_SUCCESS = 'GET_PLACE_DETAIL_SUCCESS';
export const GET_PLACE_DETAIL_FAILURE = 'GET_PLACE_DETAIL_FAILURE';

